---
version: "3.8"
services:
  service1:
    image: lab2-image:latest
    ports:
      - 3000:8080
    deploy:
      replicas: 3
  service2:
    image: lab2-image:latest
    ports:
      - 3001:8080
    deploy:
      replicas: 2
...